[package]
name = "wsh"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
genai = "0.3.5"
nix = "0.30.1"
rustyline = "16.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
thiserror = "2.0.12"
tokio = "1.47.1"
toml = "0.8.23"
xdg = "3.0.0"
